name: Run Tests
on: [push, workflow_dispatch]
jobs:
  my-job:
    name: Build doc
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: Documentation
      - name: Build Documentation
        run: make html
        working-directory: Documentation  
      - name: Store as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: Documentation/_build/html/
          