name: Run Tests
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-pdf: test-results/results.pdf
      - name: Publish test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: test-results/results.pdf